ALTER TABLE EXERCISE_WITH_REPS DROP CONSTRAINT FKEXERCISE_W919732;
ALTER TABLE EXERCISE_WITH_REPS DROP CONSTRAINT FKEXERCISE_W590838;
ALTER TABLE TRAINING_PLAN DROP CONSTRAINT FKTRAINING_P371733;
DROP TABLE IF EXISTS EXERCISE CASCADE;
DROP TABLE IF EXISTS EXERCISE_WITH_REPS CASCADE;
DROP TABLE IF EXISTS GYM_USER CASCADE;
DROP TABLE IF EXISTS TRAINING_PLAN CASCADE;
